"""Bilingual translation infrastructure for English / Traditional Chinese.

Usage in HTML generators:
    from i18n import T, T_str, bilingual

    html += f'<h2>{T("this_week")}</h2>'           # dual <span lang> pair
    msg  = T_str('gale_warning', 'zh')              # plain string for one lang
    html += bilingual('dry', '乾')                  # inline one-off
"""

from html import escape as _esc


# ── Translation dictionary ───────────────────────────────────────────────────
# Keys → {'en': English, 'zh': Traditional Chinese}
# Convention: units (kt, m, °C, hPa, km, mm), compass dirs, abbreviations
# (UTC, CST, WRF, ECMWF, CAPE, MSLP, B1–B8+) are NOT translated.

STRINGS: dict[str, dict[str, str]] = {
    # ── Page chrome & navigation ──────────────────────────────────────────
    'page_title':       {'en': 'Taiwan Sail &amp; Surf Forecast',
                         'zh': '台灣帆船衝浪預報'},
    'site_title':       {'en': '<span class="highlight">Taiwan</span> Sail &amp; Surf',
                         'zh': '<span class="highlight">台灣</span> 帆船衝浪'},
    # Multi-page nav (top-level pages)
    'nav_dashboard':    {'en': 'Dashboard',  'zh': '總覽'},
    'nav_hourly':       {'en': 'Hourly',     'zh': '逐時'},
    'nav_spots':        {'en': 'Spots',      'zh': '浪點'},
    'nav_accuracy':     {'en': 'Accuracy',   'zh': '準確度'},
    # Legacy single-page nav (kept for backwards compat)
    'nav_summary':      {'en': 'Summary',   'zh': '摘要'},
    'nav_this_week':    {'en': 'This Week',  'zh': '本週'},
    'nav_detail':       {'en': 'Detail',     'zh': '細節'},
    'last_updated':     {'en': 'Last updated', 'zh': '最後更新'},
    'stale_warning':    {'en': 'You are viewing cached data. Tap to refresh for the latest forecast.',
                         'zh': '您正在查看快取資料，點擊重新整理以獲取最新預報。'},
    'stale_old':        {'en': 'Forecast data is {h}h old. The pipeline may have failed.',
                         'zh': '預報資料已 {h} 小時未更新，系統可能發生錯誤。'},
    'refresh':          {'en': 'Refresh',    'zh': '重新整理'},
    'download_wrf':     {'en': 'Download WRF Data', 'zh': '下載 WRF 資料'},

    # ── Section titles ────────────────────────────────────────────────────
    'ai_summary_title': {'en': 'AI Forecast Summary',  'zh': 'AI 預報摘要'},
    'ai_disclaimer':    {'en': 'Generated by Claude &middot; Not a substitute for official marine forecasts',
                         'zh': '由 Claude 生成 &middot; 不可取代官方海洋預報'},
    'ai_wind':          {'en': 'Wind &amp; Sailing',    'zh': '風況與帆船'},
    'ai_waves':         {'en': 'Waves &amp; Surf',      'zh': '浪況與衝浪'},
    'ai_outlook':       {'en': 'Outlook',               'zh': '整體展望'},
    'this_week':        {'en': 'This Week',             'zh': '本週預報'},
    'filter_label':     {'en': 'Filter:',               'zh': '篩選：'},
    'filter_all':       {'en': 'All',                   'zh': '全部'},
    'filter_good_plus': {'en': 'Good+',                 'zh': '好浪以上'},
    'filter_firing':    {'en': 'Firing',                'zh': '大好浪'},
    'surf_spots':       {'en': 'Surf Spots',            'zh': '衝浪浪點'},
    'best_time_surf':   {'en': 'Best Time to Surf',     'zh': '最佳衝浪時段'},
    'detail_heading':   {'en': '6-Hourly Forecast Detail (WRF + ECMWF)',
                         'zh': '6小時預報細節 (WRF + ECMWF)'},
    'rating_caption':   {'en': '7-day surf spot ratings', 'zh': '7天浪點評等'},
    'best_time_desc':   {'en': 'Optimal 6-hour window per spot per day · Tide heights from harmonic prediction (Keelung datum)',
                         'zh': '每日每浪點最佳6小時時段 · 潮位為基隆站調和預測'},

    # ── Sailing rating labels ─────────────────────────────────────────────
    'sail_good':        {'en': 'Good',      'zh': '適航'},
    'sail_marginal':    {'en': 'Marginal',  'zh': '勉強'},
    'sail_nogo':        {'en': 'No-go',     'zh': '不宜出海'},

    # ── Surf rating labels ────────────────────────────────────────────────
    'firing':           {'en': 'Firing!',    'zh': '超讚！'},
    'good':             {'en': 'Good',       'zh': '好'},
    'marginal':         {'en': 'Marginal',   'zh': '勉強'},
    'poor':             {'en': 'Poor',       'zh': '差'},
    'flat':             {'en': 'Flat',       'zh': '無浪'},
    'dangerous':        {'en': 'Dangerous',  'zh': '危險'},
    'no_data':          {'en': 'No data',    'zh': '無資料'},

    # ── Table headers (wrf_analyze) ───────────────────────────────────────
    'th_wind':          {'en': 'Wind (kt)',  'zh': '風速 (kt)'},
    'th_gust':          {'en': 'Gust (kt)',  'zh': '陣風 (kt)'},
    'th_waves':         {'en': 'Waves (m)',  'zh': '浪高 (m)'},
    'th_period':        {'en': 'Period (s)', 'zh': '週期 (s)'},
    'th_swell':         {'en': 'Swell (m)',  'zh': '湧浪 (m)'},
    'th_wave_dir':      {'en': 'Wave Dir',   'zh': '浪向'},
    'th_pressure':      {'en': 'Pressure',   'zh': '氣壓'},
    'th_rain_6h':       {'en': 'Rain 6h',    'zh': '6h雨量'},
    'th_vis':           {'en': 'Vis (km)',   'zh': '能見度 (km)'},
    'th_temp':          {'en': 'Temp (°C)',  'zh': '溫度 (°C)'},
    'th_cloud':         {'en': 'Cloud %',    'zh': '雲量 %'},
    'th_cape':          {'en': 'CAPE',       'zh': 'CAPE'},

    # Tooltips (remain English-only in title attr — standard for technical tooltips)

    # ── Table headers (surf detail) ───────────────────────────────────────
    'th_spot':          {'en': 'Spot',        'zh': '浪點'},
    'th_best_window':   {'en': 'Best Window', 'zh': '最佳時段'},
    'th_rating':        {'en': 'Rating',      'zh': '評分'},
    'th_swell_dir':     {'en': 'Swell Dir',   'zh': '湧浪方向'},
    'th_wind_dir':      {'en': 'Wind Dir',    'zh': '風向'},
    'th_tide':          {'en': 'Tide',        'zh': '潮位'},
    'th_tide_state':    {'en': 'Tide State',  'zh': '潮況'},
    'th_swell_m':       {'en': 'Swell m',     'zh': '湧浪 m'},
    'th_t_s':           {'en': 'T s',         'zh': 'T s'},
    'th_sw_dir':        {'en': 'Sw Dir',      'zh': '浪向'},
    'th_hs_m':          {'en': 'Hs m',        'zh': 'Hs m'},
    'th_wind_kt':       {'en': 'Wind kt',     'zh': '風速 kt'},
    'th_w_dir':         {'en': 'W Dir',       'zh': '風向'},
    'th_gust_short':    {'en': 'Gust',        'zh': '陣風'},

    # ── Mobile card labels ────────────────────────────────────────────────
    'card_wind':        {'en': 'Wind',       'zh': '風'},
    'card_gust':        {'en': 'Gust',       'zh': '陣風'},
    'card_waves':       {'en': 'Waves',      'zh': '浪'},
    'card_swell':       {'en': 'Swell',      'zh': '湧浪'},
    'card_temp':        {'en': 'Temp',       'zh': '溫度'},
    'card_rain':        {'en': 'Rain 6h',    'zh': '6h雨量'},
    'card_pressure':    {'en': 'Pressure',   'zh': '氣壓'},
    'card_vis':         {'en': 'Vis',        'zh': '能見度'},
    'card_cloud':       {'en': 'Cloud',      'zh': '雲量'},

    # ── Planner table headers ─────────────────────────────────────────────
    'planner_day':         {'en': 'Day',                 'zh': '日期'},
    'planner_sailing':     {'en': '⛵ Keelung Sailing',  'zh': '⛵ 基隆航行'},
    'planner_best_surf':   {'en': '🏄 Best Surf Spot',   'zh': '🏄 最佳浪點'},
    'planner_rec':         {'en': 'Recommendation',      'zh': '建議'},

    # ── Alert messages ────────────────────────────────────────────────────
    'alert_gale':          {'en': 'Gale-force winds (B8+)', 'zh': '暴風 (B8+)'},
    'alert_near_gale':     {'en': 'Near-gale (B7)',          'zh': '強風 (B7)'},
    'alert_strong_breeze': {'en': 'Strong breeze (B6)',      'zh': '強陣風 (B6)'},
    'alert_gale_gusts':    {'en': 'Gale gusts',              'zh': '暴風陣風'},
    'alert_near_gale_gusts': {'en': 'Near-gale gusts',      'zh': '強風陣風'},
    'alert_heavy_rain':    {'en': 'Heavy rain',              'zh': '大雨'},
    'alert_mod_rain':      {'en': 'Moderate rain',           'zh': '中量降雨'},
    'alert_low_mslp':      {'en': 'Low MSLP',               'zh': '低氣壓'},
    'alert_tropical':      {'en': 'possible tropical influence', 'zh': '可能受熱帶系統影響'},
    'alert_high_cape':     {'en': 'High instability',        'zh': '大氣不穩定'},
    'alert_thunderstorm':  {'en': 'thunderstorm risk',       'zh': '雷雨風險'},
    'alert_dangerous_seas': {'en': 'Dangerous seas',         'zh': '海況危險'},
    'alert_rough':         {'en': 'Rough conditions',        'zh': '海況不佳'},
    'alert_moderate_seas': {'en': 'Moderate seas',           'zh': '中等海況'},
    'alert_consider':      {'en': 'consider not sailing',    'zh': '建議不要出海'},
    'alert_harbour':       {'en': 'harbour recommended',     'zh': '建議留港'},
    'alert_reef_in':       {'en': 'reef in',                 'zh': '收帆'},

    # ── Model shift ───────────────────────────────────────────────────────
    'model_shift':         {'en': 'Model shift vs prev run', 'zh': '與前次模式比較'},
    'vs_prev_run':         {'en': 'vs prev run',             'zh': '較前次'},

    # ── Accuracy badge ────────────────────────────────────────────────────
    'model_accuracy':      {'en': 'Model Accuracy',   'zh': '模型準確度'},

    # ── Day card labels ───────────────────────────────────────────────────
    'dry':                 {'en': 'dry',     'zh': '乾'},
    'tides':               {'en': 'Tides',   'zh': '潮汐'},
    'tides_label':         {'en': 'Tides:',  'zh': '潮汐：'},
    'daylight_label':      {'en': 'Daylight:', 'zh': '日照：'},

    # ── Recommendations ───────────────────────────────────────────────────
    'rec_sail':            {'en': '⛵ Go sailing',          'zh': '⛵ 適合航行'},
    'rec_sail_or_surf':    {'en': '⛵ Sail or 🏄 Surf',     'zh': '⛵ 航行或 🏄 衝浪'},
    'rec_go_sail_or_surf': {'en': '⛵ Go sailing or 🏄 Surf', 'zh': '⛵ 航行或 🏄 衝浪'},
    'rec_surf':            {'en': '🏄 Surf',                'zh': '🏄 衝浪'},
    'rec_marginal_maybe':  {'en': '🟡 Marginal — maybe surf', 'zh': '🟡 勉強 — 或許可衝'},
    'rec_marginal_sail':   {'en': '🟡 Marginal sailing only', 'zh': '🟡 勉強可航行'},
    'rec_maybe_surf':      {'en': '🟡 Maybe surf',          'zh': '🟡 或許可衝浪'},
    'rec_stay_home':       {'en': '🔴 Stay home',           'zh': '🔴 建議留港'},

    # ── Source legend ─────────────────────────────────────────────────────
    'source_note':         {'en': 'green <sup class="ec-sup">EC</sup> badge = ECMWF/GFS fills in where CWA WRF is absent (gust, rain, cloud, vis, CAPE)',
                            'zh': '綠色 <sup class="ec-sup">EC</sup> 標記 = ECMWF/GFS 補充 CWA WRF 缺少的資料 (陣風、雨量、雲量、能見度、CAPE)'},
    'fc_caption':          {'en': '6-hourly forecast detail — scroll horizontally on mobile',
                            'zh': '6小時預報細節 — 手機請左右滑動'},
    'delta_note':          {'en': 'Δ vs prev WRF run in brackets',
                            'zh': 'Δ 與前次 WRF 模式差異以括號顯示'},

    # ── WRF vs ECMWF ─────────────────────────────────────────────────────
    'wrf_vs_ecmwf':        {'en': 'WRF vs ECMWF',          'zh': 'WRF 對 ECMWF'},
    'overlapping_steps':   {'en': 'overlapping steps',       'zh': '重疊時間步'},

    # ── Legend (Beaufort) ─────────────────────────────────────────────────
    'legend_wind':         {'en': 'Wind (Beaufort)',  'zh': '風力 (蒲福)'},
    'legend_bf_light':     {'en': 'B1-3 &lt;11kt',   'zh': 'B1-3 &lt;11kt'},
    'legend_bf4':          {'en': 'B4 11–16',         'zh': 'B4 11–16'},
    'legend_bf5':          {'en': 'B5 17–21 reef',    'zh': 'B5 17–21 收帆'},
    'legend_bf6':          {'en': 'B6 22–27 reef in', 'zh': 'B6 22–27 收帆'},
    'legend_bf7':          {'en': 'B7 28–33 harbour', 'zh': 'B7 28–33 留港'},
    'legend_bf8':          {'en': 'B8+ ≥34 gale',    'zh': 'B8+ ≥34 暴風'},

    # ── Legend (wave Hs) ──────────────────────────────────────────────────
    'legend_hs_calm':      {'en': '&lt;0.3m',           'zh': '&lt;0.3m'},
    'legend_hs_slight':    {'en': '0.3–1m slight',      'zh': '0.3–1m 小浪'},
    'legend_hs_mod':       {'en': '1–2m moderate',       'zh': '1–2m 中浪'},
    'legend_hs_rough':     {'en': '2–3.5m rough',        'zh': '2–3.5m 大浪'},
    'legend_hs_danger':    {'en': '&gt;3.5m dangerous',  'zh': '&gt;3.5m 危險'},

    # ── Legend (wave period) ──────────────────────────────────────────────
    'legend_tp_wind':      {'en': '&lt;8s wind sea',     'zh': '&lt;8s 風浪'},
    'legend_tp_swell':     {'en': '8–12s swell',         'zh': '8–12s 湧浪'},
    'legend_tp_ocean':     {'en': '&gt;12s ocean swell', 'zh': '&gt;12s 遠洋湧浪'},

    # ── Surf legend ───────────────────────────────────────────────────────
    'surf_key':            {'en': 'Surf conditions key',  'zh': '浪況圖例'},
    'surf_firing_desc':    {'en': 'Firing (optimal dir + good swell + light wind)',
                            'zh': '超讚（最佳方向 + 好浪 + 微風）'},
    'surf_poor_dangerous': {'en': 'Poor/Dangerous',       'zh': '差/危險'},
    'surf_flat_desc':      {'en': 'Flat (&lt;0.25m swell)', 'zh': '無浪（&lt;0.25m）'},
    'dir_optimal':         {'en': 'optimal',              'zh': '最佳'},
    'dir_unfavourable':    {'en': 'unfavourable',         'zh': '不利'},
    'dir_ticks':           {'en': 'Direction ticks',      'zh': '方向標記'},
    'swell_colour':        {'en': 'Swell colour',         'zh': '湧浪顏色'},
    'surf_bf_gentle':      {'en': 'B1-3 &lt;11kt gentle',   'zh': 'B1-3 &lt;11kt 微風'},
    'surf_bf_moderate':    {'en': 'B4 11-16kt moderate',     'zh': 'B4 11-16kt 和風'},
    'surf_bf_fresh':       {'en': 'B5 17-21kt fresh',        'zh': 'B5 17-21kt 清風'},
    'surf_bf_strong':      {'en': 'B6 22-27kt strong',       'zh': 'B6 22-27kt 強風'},
    'surf_bf_near_gale':   {'en': 'B7 28-33kt near-gale',    'zh': 'B7 28-33kt 疾風'},
    'surf_bf_gale':        {'en': 'B8+ ≥34kt gale',          'zh': 'B8+ ≥34kt 暴風'},

    # ── Detailed Forecast header ──────────────────────────────────────────
    'detailed_forecast':   {'en': 'Detailed Forecast',    'zh': '詳細預報'},

    # ── Multi-page section titles ────────────────────────────────────────
    'dashboard_title':     {'en': 'Dashboard',             'zh': '總覽'},
    'hourly_title':        {'en': 'Hourly Forecast',       'zh': '逐時預報'},
    'accuracy_title':      {'en': 'Model Accuracy',        'zh': '模型準確度'},
    'current_conditions':  {'en': 'Current Conditions',    'zh': '即時觀測'},
    'cwa_live':            {'en': 'CWA Live',              'zh': '中央氣象署'},
    'quick_glance':        {'en': 'Next 24 Hours',         'zh': '未來24小時'},
    'top_spots_today':     {'en': 'Top Surf Spots Today',  'zh': '今日最佳浪點'},
    'view_details':        {'en': 'View Details',          'zh': '查看詳情'},
    'see_full_hourly':     {'en': 'See full hourly forecast', 'zh': '查看完整逐時預報'},
    'see_all_spots':       {'en': 'See all surf spots',    'zh': '查看所有浪點'},
    'wind_chart':          {'en': 'Wind &amp; Gusts',      'zh': '風速與陣風'},
    'wave_chart':          {'en': 'Waves &amp; Swell',     'zh': '浪況與湧浪'},
    'tide_chart':          {'en': 'Tide Curve',            'zh': '潮汐曲線'},
    'full_data_table':     {'en': 'Full Data Table',       'zh': '完整數據表'},
    'model_comparison':    {'en': 'Model Comparison',      'zh': '模型比較'},
    'spot_info':           {'en': 'Spot Info',             'zh': '浪點資訊'},
    'five_day_forecast':   {'en': '5-Day Forecast',        'zh': '5天預報'},
    'hourly_breakdown':    {'en': 'Hourly Breakdown',      'zh': '逐時分析'},
    'township_forecast':   {'en': 'Township Forecast',     'zh': '鄉鎮預報'},
    'facing':              {'en': 'Facing',                'zh': '朝向'},
    'optimal_wind':        {'en': 'Optimal wind',          'zh': '最佳風向'},
    'optimal_swell':       {'en': 'Optimal swell',         'zh': '最佳浪向'},
    'back_to_dashboard':   {'en': 'Dashboard',             'zh': '總覽'},
    'back_to_surf':        {'en': 'All Spots',             'zh': '所有浪點'},
    'by_horizon':          {'en': 'By Forecast Horizon',   'zh': '依預報時距'},
    'buoy_verification':   {'en': 'Buoy Verification',     'zh': '浮標驗證'},
    'verification_history': {'en': 'Verification History', 'zh': '驗證歷史'},
    'overall_rating':      {'en': 'Overall',               'zh': '整體'},
    'spot_cards':          {'en': 'Spot Cards',            'zh': '浪點卡片'},

    # ── Notification alerts ───────────────────────────────────────────────
    'notif_title':         {'en': '⚠️ Taiwan Sail & Surf Alert',
                            'zh': '⚠️ 台灣帆船衝浪警報'},
    'notif_model_run':     {'en': 'Model run',    'zh': '模式時間'},
    'notif_danger':        {'en': 'DANGER',        'zh': '危險'},
    'notif_warning':       {'en': 'WARNING',       'zh': '警告'},
    'notif_gale':          {'en': 'Gale warning',  'zh': '暴風警報'},
    'notif_strong_wind':   {'en': 'Strong wind',   'zh': '強風'},
    'notif_heavy_rain':    {'en': 'Heavy rain',    'zh': '大雨'},
    'notif_dangerous_seas': {'en': 'Dangerous seas', 'zh': '海況危險'},
    'notif_rough_seas':    {'en': 'Rough seas',    'zh': '海況不佳'},

    # ── Spot descriptions ─────────────────────────────────────────────────
    'desc_fulong':         {'en': 'Rivermouth beach break · L&R · All levels',
                            'zh': '河口沙灘浪型 · 左右跑 · 各級適合'},
    'desc_greenbay':       {'en': 'Beach break · L&R · All levels',
                            'zh': '沙灘浪型 · 左右跑 · 各級適合'},
    'desc_jinshan':        {'en': 'Beach/point · L&R · Mid tide · Beg–Inter',
                            'zh': '沙灘/礁岩 · 左右跑 · 中潮 · 初學–中級'},
    'desc_daxi':           {'en': 'Half-moon beach break · L&R · Mid-high tide · Beg–Inter',
                            'zh': '半月形沙灘 · 左右跑 · 中高潮 · 初學–中級'},
    'desc_wushih':         {'en': 'Beach break · L&R · Mid tide · All levels',
                            'zh': '沙灘浪型 · 左右跑 · 中潮 · 各級適合'},
    'desc_doublelions':    {'en': 'Beach break · L&R · Mid-high tide · All levels',
                            'zh': '沙灘浪型 · 左右跑 · 中高潮 · 各級適合'},
    'desc_chousui':        {'en': 'Point break · Left · Low-mid tide · Intermediate+',
                            'zh': '礁岩浪型 · 左跑 · 低中潮 · 中級以上'},
    # East coast
    'desc_donghe':         {'en': 'Reef break · World-class right · Advanced',
                            'zh': '礁岩浪型 · 世界級右跑 · 高級'},
    'desc_jinzun':         {'en': 'Point break · Right · All tides · Inter–Adv',
                            'zh': '礁岩浪型 · 右跑 · 各潮 · 中級–高級'},
    'desc_chenggong':      {'en': 'Beach break · L&R · All tides · All levels',
                            'zh': '沙灘浪型 · 左右跑 · 各潮 · 各級適合'},
    'desc_dulan':          {'en': 'Beach break · Mellow · All tides · Beginner',
                            'zh': '沙灘浪型 · 溫和 · 各潮 · 初學適合'},
    # South
    'desc_nanwan':         {'en': 'Beach break · L&R · All tides · All levels',
                            'zh': '沙灘浪型 · 左右跑 · 各潮 · 各級適合'},
    'desc_jialeshuei':     {'en': 'Point/reef · Powerful · Mid tide · Inter–Adv',
                            'zh': '礁岩浪型 · 有力 · 中潮 · 中級–高級'},
    'desc_baishawan':      {'en': 'Beach break · Gentle · All tides · Beginner',
                            'zh': '沙灘浪型 · 溫和 · 各潮 · 初學適合'},

    # ── Redesign UI strings ──────────────────────────────────────────────────
    'show_more_columns':   {'en': 'More columns', 'zh': '更多欄位'},
    'show_fewer_columns':  {'en': 'Fewer', 'zh': '較少'},
    'dismiss':             {'en': 'Dismiss', 'zh': '關閉'},
    'offline_notice':      {'en': 'You are offline', 'zh': '您目前離線'},
    'spots_showing':       {'en': 'showing', 'zh': '顯示中'},
    'pull_to_refresh':     {'en': 'Pull to refresh', 'zh': '下拉刷新'},
    'back_to_top':         {'en': 'Back to top', 'zh': '回到頂部'},
}

# Mapping from spot id → description i18n key
SPOT_DESC_KEYS = {
    'fulong': 'desc_fulong',
    'greenbay': 'desc_greenbay',
    'jinshan': 'desc_jinshan',
    'daxi': 'desc_daxi',
    'wushih': 'desc_wushih',
    'doublelions': 'desc_doublelions',
    'chousui': 'desc_chousui',
    # East coast
    'donghe': 'desc_donghe',
    'jinzun': 'desc_jinzun',
    'chenggong': 'desc_chenggong',
    'dulan': 'desc_dulan',
    # South
    'nanwan': 'desc_nanwan',
    'jialeshuei': 'desc_jialeshuei',
    'baishawan': 'desc_baishawan',
}


# ── Helper functions ──────────────────────────────────────────────────────────

def T(key: str) -> str:
    """Return dual-language HTML spans for the given key.

    Output: <span lang="en">English</span><span lang="zh">中文</span>
    CSS hides the inactive language based on <html lang="...">.
    """
    s = STRINGS.get(key)
    if s is None:
        return f'<span lang="en">[{_esc(key)}]</span><span lang="zh">[{_esc(key)}]</span>'
    return f'<span lang="en">{s["en"]}</span><span lang="zh">{s["zh"]}</span>'


def T_str(key: str, lang: str) -> str:
    """Return plain text for a specific language ('en' or 'zh')."""
    s = STRINGS.get(key)
    if s is None:
        return f'[{key}]'
    return s.get(lang, s.get('en', f'[{key}]'))


def bilingual(en: str, zh: str) -> str:
    """Inline bilingual span pair for one-off translations."""
    return f'<span lang="en">{_esc(en)}</span><span lang="zh">{_esc(zh)}</span>'
